### ISSUE TITLE
resampled_merge uses future data

### ISSUE THREAD

**Issue by dericdesta** [berlinguyinca/technical#7]
The nearest neighbor interpolation
```python
resampled = resampled.resample(str(interval) + 'min').interpolate(method='nearest')
```
uses data that lies in the future (see image below, 06:30 uses 08:00 of df_long).

<img width="1004" alt="technical_resample" src="https://user-images.githubusercontent.com/7849983/45590380-4a8e9c00-b937-11e8-81db-6f974ce0a3d7.png">

So I would guess that skipping the interpolation step (just merge the dataframes) and fill the NaNs with previous values would fix this issue.

**Comment by dericdesta** [comment]
I've updated to the current version, now I got this:

<img width="1013" alt="technical_resample2" src="https://user-images.githubusercontent.com/7849983/45590568-187f3900-b93b-11e8-8c11-77f5b62887f0.png">

**Comment by berlinguyinca** [comment]
ok please provide pr for it.
